import { DiMysql } from "react-icons/di";

export const AllProjectsData = [
  {
    name: "AwareNow",
    desc: "AI-Powered City Council & School Board Meeting Summaries.",
    techStack: ["Django", "OpenAI", "React", "PostgreSQL"],
    githubUrl: "",
    liveUrl: "https://www.awarenow.ai/",
    video: "no",
    thumbnail: "assets/projects/awarenow.png",
  },{
    name: "Namaste Westside",
    desc: "AI-Enabled Travel Itinerary & Event Management Platform.",
    techStack: ["Django", "OpenAI", "React", "PostgreSQL"],
    githubUrl: "",
    liveUrl: "http://20.197.2.65:8181/",
    video: "no",
    thumbnail: "assets/projects/namaste.png",
  },{
    name: "Atompass",
    desc: "Your Digital Life Secured Forever with military-grade encryption.",
    techStack: ["Node.js", "Express", "PostgreSQL", "React"],
    githubUrl: "",
    liveUrl: "https://www.atompass.com/",
    video: "no",
    thumbnail: "assets/projects/atompass.png",
  },
  {
    name: "Proxtal",
    desc: "A user-friendly platform connecting international development professionals with impactful projects worldwide",
    techStack: ["Laravel", "React", "Mysql", "Tailwind CSS"],
    liveUrl: "https://proxtal.com/",
    video: "no",
    thumbnail: "assets/projects/proxtal.png",
  },
  {
    name: "RoleMatch",
    desc: "AI-Powered Job Matching Platform",
    techStack: ["FastAPI", "Streamlit", "LangGraph", "Docker"],
    liveUrl: "https://role-match.streamlit.app/",
    video: "no",
    thumbnail: "assets/projects/role_match.png",
  },
  {
    name: "AI Chatbot",
    desc: "Mama- Your Friendly AI Chatbot",
    techStack: ["Langchain", "Streamlit"],
    liveUrl: "https://ardhendu-chatbot.streamlit.app/",
    video: "no",
    thumbnail: "assets/projects/chatbot.png",
  },
  {
    name: "ZipDJ: DJ pool",
    desc: "A DJ pool for USA and Canada with top music, advanced search, and multiple site features.",
    techStack: ["Laravel", "Mysql", "tailwind CSS", "ReactJs"],
    githubUrl: "",
    liveUrl: "https://www.zipdj.com/",
    video: "no",
    thumbnail: "assets/projects/zipdj.jpeg",
  },
  
  {
    name: "Alumni Portal",
    desc: "Developed an Alumni Portal for networking, event updates, job postings, and voting features",
    techStack: ["Laravel", "Mysql", "Bootstrap"],
    liveUrl: "https://alumni.alumnetworks.com/",
    video: "no",
    thumbnail: "assets/projects/alumni.png",
  },
  {
    name: "Admin Portal",
    desc: "Developed an Admin Portal for managing institute details and tracking alumni engagement",
    techStack: ["Laravel", "Mysql", "Bootstrap"],
    liveUrl: "https://admin.alumnetworks.com/",
    video: "no",
    thumbnail: "assets/projects/admin.png",
  },
  {
    name: "PortFolio",
    desc: "My Portfolio website showcasing my Skills and Projects",
    techStack: ["ReactJs", "Tailwind CSS", "Framer Motion"],
    liveUrl: "https://ardhendu-portfolio.netlify.app/",
    video: "no",
    thumbnail: "assets/projects/portfolio.webp",
  },
  {
    name: "Dev Focous",
    desc: "Lofi Music App to help developer focous while working",
    techStack: ["ReactJs", "Redux", "Tailwind CSS"],
    liveUrl: "https://devfocous.netlify.app/",
    video: "yes",
    thumbnail: "assets/projects/DevFocous-demo.webm",
  }
  
];
